package SDyPP.PaperLab.indice;

public class Indice {
//PARTE I: LEER SOLICITUDES DE LA COLA
	//LEER MENSAJE
	//LANZAR EXTREMCOM PARA RESPONDER SOLICITUDES 
	
	
//PARTE II: MANTENER REDUNDANCIA 
	//MODO ESPERA FALLA DEL PRINCIPAL (OTRO THREAD)
}
